title: Peter Sullivan
description: Data Engineer at the City of San Diego
theme: jekyll-theme-tactile

social:
  linkedin: www.linkedin.com/in/peter-sullivan
  email: mailto:your.pjsulliv34@gmail.com
